#!/bin/bash
set -xeuo pipefail

testctl get
export KUBECONFIG=$(pwd)/kubeconfig
for X in *; do
    ./testctl-rsync.sh $X /root/
done

# workaround docker hub ratelimits
# you get a regcred, you get a regcred!
# TODO: move this into terraform so it's not so hacky!
# runs in the background continuously trying to apply namespaces while things
# start up...
./testctl-ssh.sh -- bash regcreds.sh &
PID=$!; trap "kill $PID || true" EXIT

./testctl-ssh.sh -- terraform init
./testctl-ssh.sh -- terraform apply -auto-approve
